# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Hello-RxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hello-RxSwift
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
end
